CLASS zcl_fabap_jul2025_exer03_fvf DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_FABAP_JUL2025_EXER03_FVF IMPLEMENTATION.
ENDCLASS.
